// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBjb_Yp7J-qDqykRwSqZdiOSvXKLHlbg',
    appId: '1:72589797723:web:3d845a88f4aec88d2cd27e',
    messagingSenderId: '72589797723',
    projectId: 'tailwaggr',
    authDomain: 'tailwaggr.firebaseapp.com',
    storageBucket: 'tailwaggr.appspot.com',
    measurementId: 'G-8PYPBX6FDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXlY4MJkNqsgesUf15kZcxMZ5qMwXzRw',
    appId: '1:72589797723:android:43f0065be1d6490a2cd27e',
    messagingSenderId: '72589797723',
    projectId: 'tailwaggr',
    storageBucket: 'tailwaggr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR51SrNFtZp3vAeLhS5vQgETEnOOshEi8',
    appId: '1:72589797723:ios:91ab2a09635e82d62cd27e',
    messagingSenderId: '72589797723',
    projectId: 'tailwaggr',
    storageBucket: 'tailwaggr.appspot.com',
    iosBundleId: 'com.example.cos301Capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR51SrNFtZp3vAeLhS5vQgETEnOOshEi8',
    appId: '1:72589797723:ios:91ab2a09635e82d62cd27e',
    messagingSenderId: '72589797723',
    projectId: 'tailwaggr',
    storageBucket: 'tailwaggr.appspot.com',
    iosBundleId: 'com.example.cos301Capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRBjb_Yp7J-qDqykRwSqZdiOSvXKLHlbg',
    appId: '1:72589797723:web:870365418f6a80182cd27e',
    messagingSenderId: '72589797723',
    projectId: 'tailwaggr',
    authDomain: 'tailwaggr.firebaseapp.com',
    storageBucket: 'tailwaggr.appspot.com',
    measurementId: 'G-EC9P4JK52F',
  );

}