name: Flutter Coverage

on:
  push:
    branches: [ dev, feat/badges ]
  pull_request:
    branches: [ dev, master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.x'
    - run: flutter pub get
      working-directory: cos301_capstone
    - run: flutter test --coverage || true
      working-directory: cos301_capstone
    - run: cat ./cos301_capstone/coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./cos301_capstone/coverage/lcov.info
    - name: Finish Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        finish: true