name: Flutter Testing

on:
  push:
    branches: [ dev, feat/badges ]
  pull_request:
    branches: [ dev, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'

    - name: Install dependencies
      run: flutter pub get
      working-directory: cos301_capstone

    - name: Run tests with coverage
      run: flutter test --coverage || true
      working-directory: cos301_capstone

    - name: Install covadge
      run: flutter pub add covadge
      working-directory: cos301_capstone

    - name: Generate coverage badge
      run: flutter pub run covadge
      working-directory: cos301_capstone

    - name: Commit and push coverage badge
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./coverage_badge.svg
        git commit -m "Update coverage badge"
        git push