name: Flutter Testing

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'

    - name: Install dependencies
      run: flutter pub get
      working-directory: cos301_capstone

    - name: Run tests with coverage
      run: flutter test --coverage
      working-directory: cos301_capstone
      continue-on-error: true

    - name: Convert coverage to lcov
      run: |
        dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --package=.
      working-directory: cos301_capstone

    - name: Extract Badge URL from badges.txt
      id: extract_badge_url
      run: |
        COVERAGE_BADGE_URL=$(grep 'Code Coverage Badge URL' badges.txt | cut -d' ' -f4)
        echo "COVERAGE_BADGE_URL=$COVERAGE_BADGE_URL" >> $GITHUB_ENV

    - name: Display Badge URL
      run: echo "Coverage Badge URL is: ${{ env.COVERAGE_BADGE_URL }}"

  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create Lighthouse Results Directory
      run: mkdir -p ./lighthouse-results

    - name: Lighthouse Check
      uses: foo-software/lighthouse-check-action@v12.0.1
      with:
        urls: |
          https://tailwaggr.web.app
        outputDirectory: './lighthouse-results'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Lighthouse Badge URL
      id: extract_lighthouse_badge
      run: |
        LIGHTHOUSE_BADGE_URL=$(grep 'Lighthouse Performance Badge URL' badges.txt | cut -d' ' -f5)
        echo "LIGHTHOUSE_BADGE_URL=$LIGHTHOUSE_BADGE_URL" >> $GITHUB_ENV

    - name: Display Lighthouse Badge URL
      run: echo "Lighthouse Badge URL is: ${{ env.LIGHTHOUSE_BADGE_URL }}"
